using CleanArchitecture.Mediator;

namespace Home.Application.UseCases.CalendarSubscriptions.RefreshAllCalendarSubscriptions;

public record RefreshAllCalendarSubscriptionsInputPort() : IInputPort<IRefreshAllCalendarSubscriptionsOutputPort>;
