// <auto-generated />
using System;
using Home.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Home.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20260901094053_AddActivitySequence")]
    partial class AddActivitySequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Home.Domain.Entities.Activity", b =>
                {
                    b.Property<long>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityID"));

                    b.Property<DateTime?>("CompletedDateUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDateUTC")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DueTime")
                        .HasColumnType("time");

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("StateID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityID");

                    b.HasIndex("HouseholdID");

                    b.HasIndex("StateID");

                    b.HasIndex("UserID");

                    b.ToTable("Activity", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityContent", b =>
                {
                    b.Property<long>("ActivityContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityContentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RegionID")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ActivityContentID");

                    b.HasIndex("RegionID");

                    b.ToTable("ActivityContent", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityRegion", b =>
                {
                    b.Property<long>("ActivityRegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityRegionID"));

                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<long>("CardSectionID")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ActivityRegionID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("CardSectionID");

                    b.ToTable("ActivityRegion", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityState", b =>
                {
                    b.Property<long>("ActivityStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityStateID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ActivityStateID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("ActivityState", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityTag", b =>
                {
                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<long>("TagID")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("ActivityTag", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Announcement", b =>
                {
                    b.Property<long>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnnouncementID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.HasKey("AnnouncementID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("Announcement", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ApiAuditEntry", b =>
                {
                    b.Property<long>("ApiAuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ApiAuditEntryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApiAuditEntryID"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("ClientApplicationID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedResourceID")
                        .HasColumnType("bigint");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<short>("HttpResponseStatusCode")
                        .HasColumnType("smallint");

                    b.Property<string>("RemoteIPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestReceivedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResponseSentOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApiAuditEntryID");

                    b.HasIndex("ClientApplicationID");

                    b.HasIndex("UserID");

                    b.ToTable("ApiAuditEntry", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Audit", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditID"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("Entity")
                        .HasColumnType("bigint");

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDateUTC")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(152)
                        .HasColumnType("nvarchar(152)");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.HasIndex("Entity", "EntityID")
                        .HasDatabaseName("IX_Audit_Entity_EntityID");

                    b.ToTable("Audit", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.CardSection", b =>
                {
                    b.Property<long>("CardSectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CardSectionID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("CardSectionID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("CardSection", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ClientApplication", b =>
                {
                    b.Property<long>("ClientApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientApplicationID"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClientApplicationID");

                    b.ToTable("ClientApplication", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Household", b =>
                {
                    b.Property<long>("HouseholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HouseholdID"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LifxApiToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("HouseholdID");

                    b.ToTable("Household", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Ingredient", b =>
                {
                    b.Property<long>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngredientID"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("Unit")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IngredientID");

                    b.ToTable("Ingredient", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.IngredientNote", b =>
                {
                    b.Property<long>("NoteID")
                        .HasColumnType("bigint");

                    b.Property<long>("IngredientID")
                        .HasColumnType("bigint");

                    b.HasKey("NoteID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("IngredientNote", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Light", b =>
                {
                    b.Property<long>("LightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightID"));

                    b.Property<double>("Brightness")
                        .HasColumnType("float");

                    b.Property<bool>("HasColour")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMatrix")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMultizone")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVariableColourTemp")
                        .HasColumnType("bit");

                    b.Property<double>("Hue")
                        .HasColumnType("float");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("Kelvin")
                        .HasColumnType("int");

                    b.Property<long>("LightGroupID")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxKelvin")
                        .HasColumnType("int");

                    b.Property<int>("MinKelvin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saturation")
                        .HasColumnType("float");

                    b.Property<DateTime>("StateUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("LightID");

                    b.HasIndex("ID");

                    b.HasIndex("LightGroupID");

                    b.ToTable("Light", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightGroup", b =>
                {
                    b.Property<long>("LightGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightGroupID"));

                    b.Property<string>("ID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("LightLocationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("LightGroupID");

                    b.HasIndex("LightLocationID");

                    b.ToTable("LightGroup", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightLocation", b =>
                {
                    b.Property<long>("LightLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightLocationID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LightLocationID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("LightLocation", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightScene", b =>
                {
                    b.Property<long>("LightSceneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightSceneID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPreviousLook")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("LightSceneID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("LightScene", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightSceneState", b =>
                {
                    b.Property<long>("LightSceneStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightSceneStateID"));

                    b.Property<double>("Brightness")
                        .HasColumnType("float");

                    b.Property<double>("Hue")
                        .HasColumnType("float");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("Kelvin")
                        .HasColumnType("int");

                    b.Property<long>("LightID")
                        .HasColumnType("bigint");

                    b.Property<long>("LightSceneID")
                        .HasColumnType("bigint");

                    b.Property<double>("Saturation")
                        .HasColumnType("float");

                    b.HasKey("LightSceneStateID");

                    b.HasIndex("LightID");

                    b.HasIndex("LightSceneID");

                    b.ToTable("LightSceneState", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightSchedule", b =>
                {
                    b.Property<long>("LightScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LightScheduleID"));

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRunUTC")
                        .HasColumnType("datetime2");

                    b.Property<long>("LightSceneID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeOfDay")
                        .HasColumnType("time");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("LightScheduleID");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LightSceneID");

                    b.ToTable("LightSchedule", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.MealPlanEntry", b =>
                {
                    b.Property<long>("MealPlanEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MealPlanEntryID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MealSlotID")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.HasKey("MealPlanEntryID");

                    b.HasIndex("Date");

                    b.HasIndex("MealSlotID");

                    b.HasIndex("RecipeID");

                    b.ToTable("MealPlanEntry", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.MealSlot", b =>
                {
                    b.Property<long>("MealSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MealSlotID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartsAt")
                        .HasColumnType("time");

                    b.HasKey("MealSlotID");

                    b.HasIndex("HouseholdID", "Name")
                        .IsUnique();

                    b.ToTable("MealSlot", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Note", b =>
                {
                    b.Property<long>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoteID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("NoteID");

                    b.ToTable("Note", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Recipe", b =>
                {
                    b.Property<long>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecipeID"));

                    b.Property<long?>("Complexity")
                        .HasColumnType("bigint");

                    b.Property<int?>("CookMinutes")
                        .HasColumnType("int");

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ImageUpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("Recipe", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeImage", b =>
                {
                    b.Property<long>("RecipeImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecipeImageID"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.HasKey("RecipeImageID");

                    b.HasIndex("RecipeID")
                        .IsUnique();

                    b.ToTable("RecipeImage", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<long>("IngredientID")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("IngredientID", "RecipeID");

                    b.HasIndex("RecipeID");

                    b.ToTable("RecipeIngredient", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeMealSlot", b =>
                {
                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.Property<long>("MealSlotID")
                        .HasColumnType("bigint");

                    b.HasKey("RecipeID", "MealSlotID");

                    b.HasIndex("MealSlotID");

                    b.ToTable("RecipeMealSlot", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeNote", b =>
                {
                    b.Property<long>("NoteID")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.HasKey("NoteID", "RecipeID");

                    b.HasIndex("RecipeID");

                    b.ToTable("RecipeNote", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeStep", b =>
                {
                    b.Property<long>("RecipeStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecipeStepID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeID")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RecipeStepID");

                    b.HasIndex("RecipeID");

                    b.ToTable("RecipeStep", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<long>("ShoppingListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShoppingListID"));

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ShoppingListID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("ShoppingList", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.ShoppingListItem", b =>
                {
                    b.Property<long>("ShoppingListItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShoppingListItemID"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("InBasket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("ShoppingListID")
                        .HasColumnType("bigint");

                    b.Property<long?>("Unit")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ShoppingListItemID");

                    b.HasIndex("ShoppingListID");

                    b.ToTable("ShoppingListItem", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagID"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<long>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagID");

                    b.HasIndex("HouseholdID", "Name")
                        .IsUnique();

                    b.ToTable("Tag", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("HouseholdID")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleNames")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PasswordLastChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("User", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.UserAuthentication", b =>
                {
                    b.Property<long>("AuthenticationMetadataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuthenticationMetadataID"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientApplicationID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientApplictionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateSetUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SupersededByAuthenticationMetadataID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SupersededOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AuthenticationMetadataID");

                    b.HasIndex("ClientApplicationID");

                    b.HasIndex("ExpiresOnUTC");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("UserID");

                    b.ToTable("UserAuthentication", "home");
                });

            modelBuilder.Entity("Home.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("Activities")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Activity_Household");

                    b.HasOne("Home.Domain.Entities.ActivityState", "State")
                        .WithMany("Activities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Activity_State");

                    b.HasOne("Home.Domain.Entities.User", "User")
                        .WithMany("AssignedActivities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Activity_User");

                    b.Navigation("Household");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityContent", b =>
                {
                    b.HasOne("Home.Domain.Entities.ActivityRegion", "Region")
                        .WithMany("Fields")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityContent_ActivityRegion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityRegion", b =>
                {
                    b.HasOne("Home.Domain.Entities.Activity", "Activity")
                        .WithMany("Regions")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityRegion_Activity");

                    b.HasOne("Home.Domain.Entities.CardSection", "CardSection")
                        .WithMany("Regions")
                        .HasForeignKey("CardSectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityRegion_CardSection");

                    b.Navigation("Activity");

                    b.Navigation("CardSection");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityState", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("ActivityStates")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityState_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityTag", b =>
                {
                    b.HasOne("Home.Domain.Entities.Activity", "Activity")
                        .WithMany("Tags")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityTag_Activity");

                    b.HasOne("Home.Domain.Entities.Tag", "Tag")
                        .WithMany("Activities")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityTag_Tag");

                    b.Navigation("Activity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Home.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Announcement_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.ApiAuditEntry", b =>
                {
                    b.HasOne("Home.Domain.Entities.ClientApplication", "ClientApplication")
                        .WithMany()
                        .HasForeignKey("ClientApplicationID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ApiAuditEntry_ClientApplication");

                    b.HasOne("Home.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ApiAuditEntry_User");

                    b.Navigation("ClientApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home.Domain.Entities.Audit", b =>
                {
                    b.HasOne("Home.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Audit_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home.Domain.Entities.CardSection", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("CardSections")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CardSection_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.IngredientNote", b =>
                {
                    b.HasOne("Home.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Notes")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IngredientNote_Ingredient");

                    b.HasOne("Home.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IngredientNote_Note");

                    b.Navigation("Ingredient");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Home.Domain.Entities.Light", b =>
                {
                    b.HasOne("Home.Domain.Entities.LightGroup", "Group")
                        .WithMany("Lights")
                        .HasForeignKey("LightGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Light_Group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightGroup", b =>
                {
                    b.HasOne("Home.Domain.Entities.LightLocation", "Location")
                        .WithMany("Groups")
                        .HasForeignKey("LightLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LightGroup_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightLocation", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("LightLocations")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LightLocation_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightScene", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("LightScenes")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LightScene_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightSceneState", b =>
                {
                    b.HasOne("Home.Domain.Entities.Light", "Light")
                        .WithMany()
                        .HasForeignKey("LightID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LightSceneState_Light");

                    b.HasOne("Home.Domain.Entities.LightScene", "Scene")
                        .WithMany("States")
                        .HasForeignKey("LightSceneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LightSceneState_Scene");

                    b.Navigation("Light");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightSchedule", b =>
                {
                    b.HasOne("Home.Domain.Entities.LightScene", "Scene")
                        .WithMany()
                        .HasForeignKey("LightSceneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LightSchedule_Scene");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Home.Domain.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("Home.Domain.Entities.MealSlot", "MealSlot")
                        .WithMany()
                        .HasForeignKey("MealSlotID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MealPlanEntry_MealSlot");

                    b.HasOne("Home.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MealPlanEntry_Recipe");

                    b.Navigation("MealSlot");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.MealSlot", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("MealSlots")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MealSlot_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("Recipes")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Recipe_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeImage", b =>
                {
                    b.HasOne("Home.Domain.Entities.Recipe", "Recipe")
                        .WithOne()
                        .HasForeignKey("Home.Domain.Entities.RecipeImage", "RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeImage_Recipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Home.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_Ingredient");

                    b.HasOne("Home.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_Recipe");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeMealSlot", b =>
                {
                    b.HasOne("Home.Domain.Entities.MealSlot", "MealSlot")
                        .WithMany("Recipes")
                        .HasForeignKey("MealSlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeMealSlot_MealSlot");

                    b.HasOne("Home.Domain.Entities.Recipe", "Recipe")
                        .WithMany("MealSlots")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeMealSlot_Recipe");

                    b.Navigation("MealSlot");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeNote", b =>
                {
                    b.HasOne("Home.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeNote_Note");

                    b.HasOne("Home.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Notes")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeNote_Recipe");

                    b.Navigation("Note");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.RecipeStep", b =>
                {
                    b.HasOne("Home.Domain.Entities.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeStep_Recipe");
                });

            modelBuilder.Entity("Home.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingList_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("Home.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingListItem_ShoppingList");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Home.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("Tags")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tag_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.User", b =>
                {
                    b.HasOne("Home.Domain.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_User_Household");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Home.Domain.Entities.UserAuthentication", b =>
                {
                    b.HasOne("Home.Domain.Entities.ClientApplication", "ClientApplication")
                        .WithMany()
                        .HasForeignKey("ClientApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AuthenticationMetadata_ClientApplication");

                    b.HasOne("Home.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AuthenticationMetadata_User");

                    b.Navigation("ClientApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Regions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityRegion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Home.Domain.Entities.ActivityState", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Home.Domain.Entities.CardSection", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Home.Domain.Entities.Household", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivityStates");

                    b.Navigation("CardSections");

                    b.Navigation("LightLocations");

                    b.Navigation("LightScenes");

                    b.Navigation("MealSlots");

                    b.Navigation("Members");

                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Home.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightGroup", b =>
                {
                    b.Navigation("Lights");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightLocation", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Home.Domain.Entities.LightScene", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Home.Domain.Entities.MealSlot", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Home.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealSlots");

                    b.Navigation("Notes");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Home.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Home.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Home.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
